package mainServerClientGUI;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.InetAddress;
import javax.jmdns.JmDNS;
import javax.jmdns.ServiceInfo;
import javax.swing.JOptionPane;

/*
 * @author Nilson Francisco
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        DateOfBirth = new javax.swing.JTextField();
        therapistName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        Register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("How do you feel");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Full-name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Date of birth:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Therapist name:");

        name.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        name.setText("Your name");

        DateOfBirth.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        DateOfBirth.setText("dd/MM/yyyy");
        DateOfBirth.setToolTipText("");

        therapistName.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        therapistName.setText("Optional");
        therapistName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                therapistNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Password:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel6.setText("*At least 8 digits.");

        Register.setBackground(new java.awt.Color(204, 204, 204));
        Register.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Register.setText("Create a New User");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name)
                .addGap(7, 7, 7))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Password))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(therapistName)
                            .addComponent(DateOfBirth)
                            .addComponent(Register, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(therapistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Register)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void therapistNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_therapistNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_therapistNameActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        try{
            // Read user inputs
            String fullName = name.getText().trim();
            String dob = DateOfBirth.getText().trim();
            String therapist = therapistName.getText().trim();
            String password = new String(Password.getPassword());

            // Validate the user inputs
            if (fullName.isEmpty() || dob.isEmpty() || password.length() < 8){
                JOptionPane.showMessageDialog(null, "Please fill all required fields correctly.");
                return;
            }

            // Service discovery
            String serviceType = "_grpc._tcp.local.";
            String serviceName = "HowDoYouFeelAppServices";
            JmDNS jmdns = JmDNS.create(InetAddress.getLocalHost());
            ServiceInfo info = jmdns.getServiceInfo(serviceType, serviceName, true);
            if (info == null){
                JOptionPane.showMessageDialog(null, "Could not find the gRPC service.");
                return;
            }

            String host = info.getHostAddresses()[0];
            int port = info.getPort();
            jmdns.close();

            // Create client and call gRPC register
            MainClient client = new MainClient(host, port);
            generated.grpc.userservice.RegisterRequest registerRequest = generated.grpc.userservice.RegisterRequest.newBuilder()
                    .setUserName(fullName)
                    .setDateOfBirth(dob)
                    .setPassword(password)
                    .setTherapistName(therapist.isEmpty() ? "N/A" : therapist) // Therapist field is optional by default
                    .build();

            generated.grpc.userservice.RegisterResponse response;
                response = client.userLoginStub.registerNewUser(registerRequest);

            // Save the user to the .cvs file to keep track > use a helper method    
            if (response.getSuccess()){
                saveUserToCsv(
                    response.getUserId(),                        
                    fullName,                         
                    dob,                         
                    password,     
                    therapistName.getText()                     
                );
                JOptionPane.showMessageDialog(null, "User Registered!\nYour User ID is: " + response.getUserId());
                new LoginFrame().setVisible(true);
                dispose();
            } 
            else{
                JOptionPane.showMessageDialog(null, "Registration failed: " + response.getMessage());
            }

        } 
            catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_RegisterActionPerformed

    // Helper method to sabe the new user into a .cvs file to keep track in their entries
    private void saveUserToCsv(Integer userId, String name, String dob, String password, String therapist){
        String fileName = "users.csv";
        File file = new File(fileName);

        try (FileWriter writer = new FileWriter("data/users.csv", true)){
            if (file.length() == 0) {
                writer.append("UserID,Name,DateOfBirth,Password,TherapistName\n");
            }
            writer.append(String.format("%s,%s,%s,%s,%s\n",
                    userId,
                    name.replace(",", ";"),
                    dob,
                    password.replace(",", ";"),
                    (therapist == null || therapist.isEmpty()) ? "None" : therapist.replace(",", ";")));
        } 
        catch (IOException e){
            JOptionPane.showMessageDialog(this, "Failed to save user data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateOfBirth;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton Register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField therapistName;
    // End of variables declaration//GEN-END:variables
}
